### PR TITLE
Added Navbar feature

### PR DESCRIPTION
**Pull request by kishore223**

### CODE REVIEW

**Comment by kishore223** [comment]
mepripri can you review it?

**Comment by mepripri** [comment]
The Navbar looks fine, the links can be added as we go further.
The Signup.css change was to incorporate the compatibilities in other devices to adjust the sizes?

**Comment by kishore223** [comment]
I have adjusted the log in /sign up title and now it is compatible.

**Comment by mepripri** [comment]
Ok, then this is fine, I can also see the changes in my local, looks perfect. I am Signing off :)

**Review by mepripri — COMMENTED** [review]
Approved

**Pull request merged**
