### PR TITLE
Adding SignUp Feature in Front-End

### PR DESCRIPTION
**Pull request by mepripri**

### CODE REVIEW

**Comment by mepripri** [comment]
Adding Signup frontend and have added the POST functionality to call the backend as well.
Can you please review this.

**Review by kishore223 — CHANGES_REQUESTED** [review]
We noticed that the signup button is outside the navbar. Have you changed it?

**Comment by mepripri** [comment]
Yes kishore i have added the html and body in the App.css. Can you review it once.

**Comment by mepripri** [comment]
@Sandeep-1-Kumar , Can you please review the POST method for Signup functionality with integration to the Backend

**Comment by Sandeep-1-Kumar** [comment]
Please make sure we have a good application description on the signIn/up page

**Comment by mepripri** [comment]
@Sandeep-1-Kumar , I have made the changes, Check this PR https://github.com/fulvius31/Polyglot/pull/12

**Review by kishore223 — APPROVED** [review]

**Comment by kishore223** [comment]
The issue is fixed. I have approved.

**Comment by Sandeep-1-Kumar** [comment]
> 

it is implemented fine

**Review by Sandeep-1-Kumar — APPROVED** [review]

**Pull request merged**
