### PR TITLE
Adding Login Feature in Front-End

### PR DESCRIPTION
**Pull request by mepripri**

### CODE REVIEW

**Comment by mepripri** [comment]
Adding Login frontend and have added the POST functionality to call the backend as well.
This PR also has functions for validations of the input boxes.
Can you please review this.

**Comment by mepripri** [comment]
@Sandeep-1-Kumar , Can you please review the POST method for Login functionality with integration to the Backend

**Review by kishore223 — APPROVED** [review]
Everything is fine.

**Review by Sandeep-1-Kumar — COMMENTED** [review]
approved.

**Pull request merged**
